"""created tables

Revision ID: b676c6d74a56
Revises: 
Create Date: 2025-08-24 16:51:00.939369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b676c6d74a56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('analytics_type', sa.Enum('CRIME_TREND', 'HOTSPOT_ANALYSIS', 'RESPONSE_TIME', 'RESOLUTION_RATE', 'USER_ENGAGEMENT', name='analyticstype'), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('sub_county', sa.String(length=100), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('count_value', sa.Integer(), nullable=True),
    sa.Column('category_breakdown', sa.Text(), nullable=True),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analytics_metric', 'analytics', ['metric_name', 'analytics_type'], unique=False)
    op.create_index('idx_analytics_period', 'analytics', ['period_start', 'period_end'], unique=False)
    op.create_index('idx_analytics_time_type', 'analytics', ['period_start', 'analytics_type'], unique=False)
    op.create_index('idx_analytics_type_location', 'analytics', ['analytics_type', 'county', 'sub_county'], unique=False)
    op.create_index(op.f('ix_analytics_analytics_type'), 'analytics', ['analytics_type'], unique=False)
    op.create_index(op.f('ix_analytics_county'), 'analytics', ['county'], unique=False)
    op.create_index(op.f('ix_analytics_created_at'), 'analytics', ['created_at'], unique=False)
    op.create_index(op.f('ix_analytics_created_by_id'), 'analytics', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_analytics_deleted_at'), 'analytics', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_analytics_id'), 'analytics', ['id'], unique=False)
    op.create_index(op.f('ix_analytics_metric_name'), 'analytics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_analytics_period_end'), 'analytics', ['period_end'], unique=False)
    op.create_index(op.f('ix_analytics_period_start'), 'analytics', ['period_start'], unique=False)
    op.create_index(op.f('ix_analytics_sub_county'), 'analytics', ['sub_county'], unique=False)
    op.create_index(op.f('ix_analytics_updated_at'), 'analytics', ['updated_at'], unique=False)
    op.create_index(op.f('ix_analytics_updated_by_id'), 'analytics', ['updated_by_id'], unique=False)
    op.create_table('comments',
    sa.Column('crime_report_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('is_status_update', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comment_internal_status', 'comments', ['is_internal', 'is_status_update'], unique=False)
    op.create_index('idx_comment_report_author', 'comments', ['crime_report_id', 'author_id'], unique=False)
    op.create_index(op.f('ix_comments_author_id'), 'comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_comments_created_at'), 'comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_comments_created_by_id'), 'comments', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_comments_crime_report_id'), 'comments', ['crime_report_id'], unique=False)
    op.create_index(op.f('ix_comments_deleted_at'), 'comments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_is_internal'), 'comments', ['is_internal'], unique=False)
    op.create_index(op.f('ix_comments_is_status_update'), 'comments', ['is_status_update'], unique=False)
    op.create_index(op.f('ix_comments_updated_at'), 'comments', ['updated_at'], unique=False)
    op.create_index(op.f('ix_comments_updated_by_id'), 'comments', ['updated_by_id'], unique=False)
    op.create_table('crime_reports',
    sa.Column('report_number', sa.String(length=50), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('THEFT', 'ASSAULT', 'BURGLARY', 'ROBBERY', 'FRAUD', 'CYBERCRIME', 'DOMESTIC_VIOLENCE', 'DRUG_RELATED', 'TRAFFIC_VIOLATION', 'VANDALISM', 'MURDER', 'KIDNAPPING', 'SEXUAL_ASSAULT', 'OTHER', name='crimecategory'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='crimeseverity'), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_INVESTIGATION', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', name='reportstatus'), nullable=False),
    sa.Column('assigned_officer_id', sa.UUID(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('suspect_description', sa.Text(), nullable=True),
    sa.Column('witness_count', sa.Integer(), nullable=True),
    sa.Column('estimated_loss', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crime_report_assigned_status', 'crime_reports', ['assigned_officer_id', 'status'], unique=False)
    op.create_index('idx_crime_report_location_category', 'crime_reports', ['location_id', 'category'], unique=False)
    op.create_index('idx_crime_report_priority', 'crime_reports', ['priority_score', 'is_emergency'], unique=False)
    op.create_index('idx_crime_report_reporter_status', 'crime_reports', ['reporter_id', 'status'], unique=False)
    op.create_index('idx_crime_report_severity_emergency', 'crime_reports', ['severity', 'is_emergency'], unique=False)
    op.create_index('idx_crime_report_status_category', 'crime_reports', ['status', 'category'], unique=False)
    op.create_index('idx_crime_report_verification', 'crime_reports', ['is_verified', 'status'], unique=False)
    op.create_index(op.f('ix_crime_reports_assigned_officer_id'), 'crime_reports', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_crime_reports_category'), 'crime_reports', ['category'], unique=False)
    op.create_index(op.f('ix_crime_reports_created_at'), 'crime_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_crime_reports_created_by_id'), 'crime_reports', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_crime_reports_deleted_at'), 'crime_reports', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_crime_reports_id'), 'crime_reports', ['id'], unique=False)
    op.create_index(op.f('ix_crime_reports_is_anonymous'), 'crime_reports', ['is_anonymous'], unique=False)
    op.create_index(op.f('ix_crime_reports_is_emergency'), 'crime_reports', ['is_emergency'], unique=False)
    op.create_index(op.f('ix_crime_reports_is_verified'), 'crime_reports', ['is_verified'], unique=False)
    op.create_index(op.f('ix_crime_reports_location_id'), 'crime_reports', ['location_id'], unique=False)
    op.create_index(op.f('ix_crime_reports_priority_score'), 'crime_reports', ['priority_score'], unique=False)
    op.create_index(op.f('ix_crime_reports_report_number'), 'crime_reports', ['report_number'], unique=True)
    op.create_index(op.f('ix_crime_reports_reporter_id'), 'crime_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_crime_reports_severity'), 'crime_reports', ['severity'], unique=False)
    op.create_index(op.f('ix_crime_reports_status'), 'crime_reports', ['status'], unique=False)
    op.create_index(op.f('ix_crime_reports_title'), 'crime_reports', ['title'], unique=False)
    op.create_index(op.f('ix_crime_reports_updated_at'), 'crime_reports', ['updated_at'], unique=False)
    op.create_index(op.f('ix_crime_reports_updated_by_id'), 'crime_reports', ['updated_by_id'], unique=False)
    op.create_table('evidence',
    sa.Column('crime_report_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.Enum('PHOTO', 'VIDEO', 'AUDIO', 'DOCUMENT', 'OTHER', name='evidencetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('chain_of_custody', sa.Text(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evidence_hash_type', 'evidence', ['file_hash', 'evidence_type'], unique=False)
    op.create_index('idx_evidence_processing', 'evidence', ['is_processed', 'evidence_type'], unique=False)
    op.create_index('idx_evidence_report_type', 'evidence', ['crime_report_id', 'evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_created_by_id'), 'evidence', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_evidence_crime_report_id'), 'evidence', ['crime_report_id'], unique=False)
    op.create_index(op.f('ix_evidence_deleted_at'), 'evidence', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_file_hash'), 'evidence', ['file_hash'], unique=True)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_is_processed'), 'evidence', ['is_processed'], unique=False)
    op.create_index(op.f('ix_evidence_mime_type'), 'evidence', ['mime_type'], unique=False)
    op.create_index(op.f('ix_evidence_updated_at'), 'evidence', ['updated_at'], unique=False)
    op.create_index(op.f('ix_evidence_updated_by_id'), 'evidence', ['updated_by_id'], unique=False)
    op.create_table('locations',
    sa.Column('latitude', sa.Float(precision=10), nullable=False),
    sa.Column('longitude', sa.Float(precision=11), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('sub_county', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('location_type', sa.Enum('CRIME_SCENE', 'LANDMARK', 'POLICE_STATION', 'HOSPITAL', 'SCHOOL', 'RESIDENTIAL', 'COMMERCIAL', 'PUBLIC_SPACE', name='locationtype'), nullable=False),
    sa.Column('landmark', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('accuracy_meters', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_location_admin', 'locations', ['county', 'sub_county', 'city'], unique=False)
    op.create_index('idx_location_coordinates', 'locations', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_location_type_county', 'locations', ['location_type', 'county'], unique=False)
    op.create_index(op.f('ix_locations_city'), 'locations', ['city'], unique=False)
    op.create_index(op.f('ix_locations_county'), 'locations', ['county'], unique=False)
    op.create_index(op.f('ix_locations_created_at'), 'locations', ['created_at'], unique=False)
    op.create_index(op.f('ix_locations_created_by_id'), 'locations', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_locations_deleted_at'), 'locations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_latitude'), 'locations', ['latitude'], unique=False)
    op.create_index(op.f('ix_locations_location_type'), 'locations', ['location_type'], unique=False)
    op.create_index(op.f('ix_locations_longitude'), 'locations', ['longitude'], unique=False)
    op.create_index(op.f('ix_locations_sub_county'), 'locations', ['sub_county'], unique=False)
    op.create_index(op.f('ix_locations_updated_at'), 'locations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_locations_updated_by_id'), 'locations', ['updated_by_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('crime_report_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Enum('REPORT_SUBMITTED', 'REPORT_UPDATED', 'REPORT_ASSIGNED', 'REPORT_RESOLVED', 'EMERGENCY_ALERT', 'SYSTEM_NOTIFICATION', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'DELIVERED', 'READ', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_via_email', sa.Boolean(), nullable=False),
    sa.Column('sent_via_sms', sa.Boolean(), nullable=False),
    sa.Column('sent_via_push', sa.Boolean(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_read_status', 'notifications', ['is_read', 'status'], unique=False)
    op.create_index('idx_notification_report_type', 'notifications', ['crime_report_id', 'notification_type'], unique=False)
    op.create_index('idx_notification_type_urgent', 'notifications', ['notification_type', 'is_urgent'], unique=False)
    op.create_index('idx_notification_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_by_id'), 'notifications', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_notifications_crime_report_id'), 'notifications', ['crime_report_id'], unique=False)
    op.create_index(op.f('ix_notifications_deleted_at'), 'notifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_is_urgent'), 'notifications', ['is_urgent'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_updated_at'), 'notifications', ['updated_at'], unique=False)
    op.create_index(op.f('ix_notifications_updated_by_id'), 'notifications', ['updated_by_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'POLICE_OFFICER', 'ADMIN', 'ANALYST', 'DISPATCHER', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', name='userstatus'), nullable=False),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('badge_number', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('rank', sa.String(length=50), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('sub_county', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('badge_number', name='uq_user_badge'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('phone_number', name='uq_user_phone')
    )
    op.create_index('idx_user_location', 'users', ['county', 'sub_county'], unique=False)
    op.create_index('idx_user_role_status', 'users', ['role', 'status'], unique=False)
    op.create_index('idx_user_verification', 'users', ['is_verified', 'email_verified', 'phone_verified'], unique=False)
    op.create_index(op.f('ix_users_badge_number'), 'users', ['badge_number'], unique=True)
    op.create_index(op.f('ix_users_county'), 'users', ['county'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_created_by_id'), 'users', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_sub_county'), 'users', ['sub_county'], unique=False)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_index(op.f('ix_users_updated_by_id'), 'users', ['updated_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_updated_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_sub_county'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_by_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_county'), table_name='users')
    op.drop_index(op.f('ix_users_badge_number'), table_name='users')
    op.drop_index('idx_user_verification', table_name='users')
    op.drop_index('idx_user_role_status', table_name='users')
    op.drop_index('idx_user_location', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_updated_by_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_updated_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_urgent'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_deleted_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_crime_report_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_by_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notification_user_status', table_name='notifications')
    op.drop_index('idx_notification_type_urgent', table_name='notifications')
    op.drop_index('idx_notification_report_type', table_name='notifications')
    op.drop_index('idx_notification_read_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_locations_updated_by_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_updated_at'), table_name='locations')
    op.drop_index(op.f('ix_locations_sub_county'), table_name='locations')
    op.drop_index(op.f('ix_locations_longitude'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_type'), table_name='locations')
    op.drop_index(op.f('ix_locations_latitude'), table_name='locations')
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_deleted_at'), table_name='locations')
    op.drop_index(op.f('ix_locations_created_by_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_created_at'), table_name='locations')
    op.drop_index(op.f('ix_locations_county'), table_name='locations')
    op.drop_index(op.f('ix_locations_city'), table_name='locations')
    op.drop_index('idx_location_type_county', table_name='locations')
    op.drop_index('idx_location_coordinates', table_name='locations')
    op.drop_index('idx_location_admin', table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_evidence_updated_by_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_updated_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_mime_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_is_processed'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_file_hash'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_deleted_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_crime_report_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_by_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_index('idx_evidence_report_type', table_name='evidence')
    op.drop_index('idx_evidence_processing', table_name='evidence')
    op.drop_index('idx_evidence_hash_type', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_crime_reports_updated_by_id'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_updated_at'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_title'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_status'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_severity'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_reporter_id'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_report_number'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_priority_score'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_location_id'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_is_verified'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_is_emergency'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_is_anonymous'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_id'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_deleted_at'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_created_by_id'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_created_at'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_category'), table_name='crime_reports')
    op.drop_index(op.f('ix_crime_reports_assigned_officer_id'), table_name='crime_reports')
    op.drop_index('idx_crime_report_verification', table_name='crime_reports')
    op.drop_index('idx_crime_report_status_category', table_name='crime_reports')
    op.drop_index('idx_crime_report_severity_emergency', table_name='crime_reports')
    op.drop_index('idx_crime_report_reporter_status', table_name='crime_reports')
    op.drop_index('idx_crime_report_priority', table_name='crime_reports')
    op.drop_index('idx_crime_report_location_category', table_name='crime_reports')
    op.drop_index('idx_crime_report_assigned_status', table_name='crime_reports')
    op.drop_table('crime_reports')
    op.drop_index(op.f('ix_comments_updated_by_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_updated_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_status_update'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_internal'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_deleted_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_crime_report_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_by_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_created_at'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_id'), table_name='comments')
    op.drop_index('idx_comment_report_author', table_name='comments')
    op.drop_index('idx_comment_internal_status', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_analytics_updated_by_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_updated_at'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_sub_county'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_period_start'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_period_end'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_metric_name'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_deleted_at'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_created_by_id'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_created_at'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_county'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_analytics_type'), table_name='analytics')
    op.drop_index('idx_analytics_type_location', table_name='analytics')
    op.drop_index('idx_analytics_time_type', table_name='analytics')
    op.drop_index('idx_analytics_period', table_name='analytics')
    op.drop_index('idx_analytics_metric', table_name='analytics')
    op.drop_table('analytics')
    # ### end Alembic commands ###
